# Central Train & Station Datasets for SaralYatra Backend

STATIONS = [
  {"code": "BCT", "name": "Mumbai Central", "city": "Mumbai", "state": "Maharashtra"},
  {"code": "ADI", "name": "Ahmedabad Junction", "city": "Ahmedabad", "state": "Gujarat"},
  {"code": "NDLS", "name": "New Delhi", "city": "New Delhi", "state": "Delhi"},
  {"code": "NZM", "name": "Hazrat Nizamuddin", "city": "Delhi", "state": "Delhi"},
  {"code": "PUNE", "name": "Pune Junction", "city": "Pune", "state": "Maharashtra"},
  {"code": "MAS", "name": "Chennai Central", "city": "Chennai", "state": "Tamil Nadu"},
  {"code": "SBC", "name": "KSR Bengaluru", "city": "Bengaluru", "state": "Karnataka"},
  {"code": "JP", "name": "Jaipur Junction", "city": "Jaipur", "state": "Rajasthan"},
  {"code": "HWH", "name": "Howrah Junction", "city": "Kolkata", "state": "West Bengal"},
]

TRAINS = [
  {
    "id": "T22435",
    "number": "22435",
    "name": "Vande Bharat Express",
    "type": "Vande Bharat",
    "fromCode": "BCT",
    "from": "Mumbai Central",
    "toCode": "ADI",
    "to": "Ahmedabad Junction",
    "departureTime": "06:10",
    "arrivalTime": "12:40",
    "duration": "6h 30m",
    "durationMins": 390,
    "distance": 492,
    "runsOn": "Daily",
    "daysOfWeek": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "classes": [
      {"code": "CC", "name": "Chair Car", "fare": 1250, "available": 42, "status": "AVAILABLE"},
      {"code": "EC", "name": "Executive Chair Car", "fare": 2455, "available": 8, "status": "AVAILABLE"}
    ],
    "amenities": ["wifi", "catering", "ac", "charging"],
    "rating": 4.6,
    "onTimePercentage": 91,
    "baseScore": 92
  },
  {
    "id": "T12009",
    "number": "12009",
    "name": "Shatabdi Express",
    "type": "Shatabdi",
    "fromCode": "BCT",
    "from": "Mumbai Central",
    "toCode": "ADI",
    "to": "Ahmedabad Junction",
    "departureTime": "06:25",
    "arrivalTime": "13:10",
    "duration": "6h 45m",
    "durationMins": 405,
    "distance": 492,
    "runsOn": "Except Sunday",
    "daysOfWeek": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "classes": [
      {"code": "CC", "name": "Chair Car", "fare": 890, "available": 120, "status": "AVAILABLE"},
      {"code": "EC", "name": "Executive Chair Car", "fare": 1780, "available": 24, "status": "AVAILABLE"}
    ],
    "amenities": ["catering", "ac", "charging"],
    "rating": 4.3,
    "onTimePercentage": 84,
    "baseScore": 78
  },
  {
    "id": "T19010",
    "number": "19010",
    "name": "Saurashtra Mail",
    "type": "Mail / Express",
    "fromCode": "BCT",
    "from": "Mumbai Central",
    "toCode": "ADI",
    "to": "Ahmedabad Junction",
    "departureTime": "21:50",
    "arrivalTime": "07:15",
    "duration": "9h 25m",
    "durationMins": 565,
    "distance": 492,
    "runsOn": "Daily",
    "daysOfWeek": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "classes": [
      {"code": "SL", "name": "Sleeper", "fare": 295, "available": 310, "status": "AVAILABLE"},
      {"code": "3A", "name": "3 Tier AC", "fare": 745, "available": 88, "status": "AVAILABLE"},
      {"code": "2A", "name": "2 Tier AC", "fare": 1095, "available": 30, "status": "AVAILABLE"},
      {"code": "1A", "name": "First Class AC", "fare": 1840, "available": 4, "status": "LIMITED"}
    ],
    "amenities": ["ac", "bedding", "charging"],
    "rating": 3.9,
    "onTimePercentage": 76,
    "baseScore": 58
  },
  {
    "id": "T12951",
    "number": "12951",
    "name": "Mumbai Rajdhani Express",
    "type": "Rajdhani",
    "fromCode": "BCT",
    "from": "Mumbai Central",
    "toCode": "NDLS",
    "to": "New Delhi",
    "departureTime": "17:00",
    "arrivalTime": "08:35",
    "duration": "15h 35m",
    "durationMins": 935,
    "distance": 1384,
    "runsOn": "Daily",
    "daysOfWeek": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "classes": [
      {"code": "3A", "name": "3 Tier AC", "fare": 1820, "available": 74, "status": "AVAILABLE"},
      {"code": "2A", "name": "2 Tier AC", "fare": 2640, "available": 22, "status": "AVAILABLE"},
      {"code": "1A", "name": "First Class AC", "fare": 4450, "available": 4, "status": "LIMITED"}
    ],
    "amenities": ["catering", "ac", "bedding", "charging"],
    "rating": 4.5,
    "onTimePercentage": 88,
    "baseScore": 86
  },
  {
    "id": "T12027",
    "number": "12027",
    "name": "Chennai Shatabdi Express",
    "type": "Shatabdi",
    "fromCode": "MAS",
    "from": "Chennai Central",
    "toCode": "SBC",
    "to": "KSR Bengaluru",
    "departureTime": "06:00",
    "arrivalTime": "11:00",
    "duration": "5h 00m",
    "durationMins": 300,
    "distance": 362,
    "runsOn": "Daily",
    "daysOfWeek": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "classes": [
      {"code": "CC", "name": "Chair Car", "fare": 580, "available": 180, "status": "AVAILABLE"},
      {"code": "EC", "name": "Executive Chair Car", "fare": 1155, "available": 28, "status": "AVAILABLE"}
    ],
    "amenities": ["catering", "ac", "charging"],
    "rating": 4.4,
    "onTimePercentage": 86,
    "baseScore": 82
  },
  {
    "id": "T12263",
    "number": "12263",
    "name": "Pune Duronto Express",
    "type": "Duronto",
    "fromCode": "PUNE",
    "from": "Pune Junction",
    "toCode": "NZM",
    "to": "Hazrat Nizamuddin",
    "departureTime": "16:50",
    "arrivalTime": "08:55",
    "duration": "16h 05m",
    "durationMins": 965,
    "distance": 1202,
    "runsOn": "Mon, Wed, Fri, Sun",
    "daysOfWeek": ["Mon", "Wed", "Fri", "Sun"],
    "classes": [
      {"code": "SL", "name": "Sleeper", "fare": 595, "available": 210, "status": "AVAILABLE"},
      {"code": "3A", "name": "3 Tier AC", "fare": 1540, "available": 62, "status": "AVAILABLE"},
      {"code": "2A", "name": "2 Tier AC", "fare": 2210, "available": 18, "status": "AVAILABLE"}
    ],
    "amenities": ["catering", "ac", "bedding"],
    "rating": 4.1,
    "onTimePercentage": 72,
    "baseScore": 65
  }
]
